#+Title: Week 0 - Functions
#+date:<2024-10-08 Tue>
#+author: mario

* Lecture Note Begins
** Writing the first Program
- Started off with hello world program.
- Running that program through interpretor via terminal.

** Introduction to functions.
- Generally there are predetermined set of intructions that a programming language already knows.
- A programmer can just call them, through their names and syntax.
- print() is a function.
- Arguments are inputs to a funciton that changes it behavior.
  Sometimes those changes are exactly what we need.
  Ex: If I change te value of radius, the output of area of circle program will change.
      Radius is the argument of the area of the function.
** What are bugs
- Side Effects of a program are things like displaying text, visuals and audible beeps.
- A mistake in a program is called bugs. Various types like syntax, logical, semantic, resource, etc.
- A computer expects things to be done in a certain way, if it does not happen, it throws an error.

** Return Values & Variables
- Some value or data that the function just hands out when it is called is called a value.
