CFLAGS=-Wall -g
clean:
	 rm -f 000
	 rm -f 001
	 rm -f 002
	 rm -f 003
	 rm -f 003_1
	 rm -f 004
	 rm -f 004_1
	 rm -f 005
	 rm -f 005_1
	 rm -f 006
	 rm -f 007
	 rm -f 008
	 rm -f 009
	 rm -f 009_1
	 rm -f 010
	 rm -f 011
